### ISSUE TITLE
Error: "data did not match any variant of untagged enum PackageMaintainers at line 2361 column 7"

### ISSUE THREAD

**Issue by usmcamp0811** [louib/nix2sbom#21]
Saw your flake on FlakeHub and thought I would give it a go. I added it to my config and tried running:

```sh
nix2sbom --current-system
```

and I got the following error:

```sh
[00:00:00.000] (7f28fe0877c0) INFO   Getting the derivations from the current system.
[00:00:01.197] (7f28fe0877c0) INFO   Found 10375 derivations
[00:00:01.197] (7f28fe0877c0) INFO   Getting the metadata for packages in the Nix store
Error: "data did not match any variant of untagged enum PackageMaintainers at line 2361 column 7"
```

I tried some more things and got the same or similar looking errors:

```sh
╭─mcamp on butler in ~/code/campground-nvim on master🔥
╰─🚧 nix2sbom -f .#
[00:00:00.000] (7fc8d82b47c0) INFO   Getting the derivations from file .#.
[00:00:02.779] (7fc8d82b47c0) INFO   Found 4344 derivations
[00:00:02.779] (7fc8d82b47c0) INFO   Getting the metadata for packages in the Nix store
Error: "data did not match any variant of untagged enum PackageMaintainers at line 2361 column 7"
╭─mcamp on butler in ~/code/campground-nvim on master🔥
╰─🚧 cd ../vault-secrets 
╭─mcamp on butler in ~/code/vault-secrets on main✔️
╰─🚧 nix2sbom -f .#     
[00:00:00.000] (7f0a885e47c0) INFO   Getting the derivations from file .#.
[00:00:00.448] (7f0a885e47c0) INFO   Found 654 derivations
[00:00:00.448] (7f0a885e47c0) INFO   Getting the metadata for packages in the Nix store
Error: "data did not match any variant of untagged enum PackageMaintainers at line 2361 column 7"
```

`campground-nvim` and `vault-secrets` are flakes of mine, the `nvim` one is based on `nixvim` and the other is a simple shell script flake I was playing with the other night.

I very well might be doing something dumb, because I only marginally know what I'm doing. So if I am way out in left field let me know..

**Comment by louib** [comment]
@usmcamp0811 thanks for reporting the issue!

This step is fetching the metadata for the packages in your store, which explains why I wasn't able to reproduce locally.
You can generate the metadata information for your Nix store with the following command:
```
nix-env -q -a --meta --json '.*' > packages-metadata.json
```

You can then call `nix2sbom` with the `--metadata-path` option to use a pre-generated metadata, for example:
```
nix2sbom -f .# --metadata-path packages-metadata.json
```

If you could do the following two commands and send me the derivation that is located at line `2361` (or whatever line it will be once you try again), that would help me troubleshooting faster. Thanks a lot!

**Comment by usmcamp0811** [comment]
I tried running those commands and got:

```sh
╭─mcamp on butler in /config on nixos🔥
╰─🚧 nix-env -q -a --meta --json '.*' > packages-metadata.json
╭─mcamp on butler in /config on nixos🔥
╰─🚧 nix2sbom -f .# --metadata-path packages-metadata.json
[00:00:00.000] (7fc99ef0f7c0) INFO   Getting the derivations from file .#.
Error: Custom { kind: UnexpectedEof, error: Error("EOF while parsing a value", line: 1, column: 0) }
╭─mcamp on butler in /config on nixos🔥
╰─🚧 nix2sbom -f .# --metadata-path /config/packages-metadata.json
[00:00:00.000] (7f40b6af07c0) INFO   Getting the derivations from file .#.
Error: Custom { kind: UnexpectedEof, error: Error("EOF while parsing a value", line: 1, column: 0) }
╭─mcamp on butler in /config on nixos🔥
╰─🚧 nix2sbom -f .#butler --metadata-path /config/packages-metadata.json
[00:00:00.000] (7fec1f50b7c0) INFO   Getting the derivations from file .#butler.
Error: Custom { kind: UnexpectedEof, error: Error("EOF while parsing a value", line: 1, column: 0) }
```

I dunno about uploading that `packages-metadata.json` its `128MB`. If you need it I can figure a place to put it.

**Comment by louib** [comment]
@usmcamp0811 thanks for the snippet! I was able to capture the bug in a unit test and provide a fix in https://github.com/louib/nix2sbom/pull/24.

I'm not sure why you were getting the `UnexpectedEof` errors when trying to use the `--metadata-path` path option :thinking: I tried reproducing locally but didn't get that error.

**Comment by louib** [comment]
@usmcamp0811 please give it another shot with version `louib/nix2sbom/0.1.106+rev-db34541fdf1017060bfaefa60c3b8867c7518aa6`, which should be available from Flakehub now.

**Comment by louib** [comment]
@usmcamp0811 I'm going to close this one, let me know if you run into the issue again.
