### ISSUE TITLE
nix2sbom appears to be incompatible with profiles

### ISSUE THREAD

**Issue by kjeremy** [louib/nix2sbom#31]
`get_packages` calls `nix-env` which is failing for me. If I try it on the command line I get the following:

```console
[jkolb@nixos:~]$ nix-env -q --meta --json '.*'
error: profile '/nix/var/nix/profiles/per-user/jkolb/profile' is incompatible with 'nix-env'; please use 'nix profile' instead
```

**Comment by louib** [comment]
@kjeremy I'm curious to know why you closed this issue :thinking:

**Comment by kjeremy** [comment]
I mistyped the command and that's how I triggered the error.
